name: Sync Code to Next.js React Playground

on:
  push:
    branches:
      - dev

jobs:
  sync-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout TypeScript Playground
        uses: actions/checkout@v2
        with:
          repository: serhataydus/typescript-playground
          ref: dev

      - name: Copy Code to Next.js React Playground
        run: |
          cp -r ./* ../nextjs-react-playground
        working-directory: typescript-playground

      - name: Commit and Push to Next.js React Playground
        run: |
          cd ../nextjs-react-playground
          git config user.email "your-email@example.com"
          git config user.name "Your Name"
          git add .
          git commit -m "Sync code from TypeScript Playground"
          git push origin dev
