# A Projesi İçin .github/workflows/build.yml
name: Build and Deploy A Project

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Next.js Project
        run: |
          cp -r infrastructure/* path/to/nextjs/
          cd path/to/nextjs
          npm install
          npm run build
