name: Update Projects

on:
  push:
    branches:
      - dev

jobs:
  update-projects:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Nextjs-React-Playgorund
        run: |
          cd typescript-playgorund
          npm install https://github.com/serhataydus/nextjs-react-playgorund#dev
        working-directory: ${{ github.workspace }}
