name: Update Projects

on:
  push:
    branches:
      - dev

jobs:
  update-projects:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update X Project
        run: |
          cd typescript-playgorund

          # Check if the directory exists, if not, create it
          if [ ! -d "typescript-playgorund" ]; then
            mkdir typescript-playgorund
          fi

          npm install https://github.com/serhataydus/typescript-playgorund#dev
        working-directory: ${{ github.workspace }}
