name: Sync Code to Another Repository

on:
  push:
    branches:
      - dev

jobs:
  sync-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2
        with:
          repository: serhataydus/typescript-playground # Correct repository name
          ref: dev

      - name: Set up Git in Source Repository
        run: |
          git config user.email "serhataydus@hotmail.com"
          git config user.name "Serhat Aydus"

      - name: Copy Code to Target Repository
        run: |
          mkdir ../nextjs-react-playground  # Correct target repository name
          cp -r * ../nextjs-react-playground

      - name: Set up Git in Target Repository
        run: |
          cd ../nextjs-react-playground
          git init
          git remote add origin https://github.com/serhataydus/nextjs-react-playground.git  # Correct target repository URL
          git add .
          git commit -m "Sync code from Source Repository"
          git push -u --force origin dev
